environment:
  name: kaggle_gpu
  device: cuda

optimization:
  n_initial: 16
  n_iterations: 10
  candidates_per_iteration: 4
  resume_from_csv: false

training:
  max_epochs: 10
  patience: 5
  batch_size: 4
  num_workers: 2

smoke_test:
  enabled: false

paths:
  project_root: "/kaggle/working/breast_cancer_mobo"
  
  vindr_images: "/kaggle/input/datasets/davidolaboye/mobo-vindr/vindr_mammo_dataset_dave/images"
  vindr_csv: "/kaggle/input/datasets/davidolaboye/mobo-vindr/vindr_mammo_dataset_dave/metadata/stratified_selection.csv"

  inbreast_dicom_dir: "/kaggle/input/datasets/ramanathansp20/inbreast-dataset/INbreast Release 1.0/AllDICOMs"
  inbreast_metadata: "/kaggle/input/datasets/ramanathansp20/inbreast-dataset/INbreast Release 1.0/INbreast.xls"

  csv_resume_path: ""
  inbreast_split_info_path: ""

  output_dir: "/kaggle/working/results/botorch_mobo"